apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Descripcion de aplicacion python
  annotations:
    github.com/project-slug: aldo2510/pythonapp
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental